AWSTemplateFormatVersion: '2010-09-09'
Description: Organization Exporter Lambda


Parameters:
  S3BucketPrefix:
    Type: String
    Description: >-
      Must contain only lowercase letters, numbers, periods (.) and hyphens (-)
    Default: lambda-code-bucket
  LamdaZipFileKey:
    Type: String
    Description: >-
      Lambda-zip with the Config setup, must be uploaded to the S3 in advance
    Default: organization-exporter/organization-exporter-0.0.1.zip
  TargetBucket:
    Type: String
    Description: Name of the s3 bucket where the object should be uploaded to
    Default: "export-ACCOUNTID-orga"
  ObjectName:
    Type: String
    Description: Name of the object on s3
    Default: "aws-organization.json"
  ScheduleExpression:
    Type: String
    AllowedPattern: >-
      ^(rate\(((1 (hour|minute|day))|(\d+
      (hours|minutes|days)))\))|(cron\(\s*($|#|\w+\s*=|(\?|\*|(?:[0-5]?\d)(?:(?:-|/|\,)(?:[0-5]?\d))?(?:,(?:[0-5]?\d)(?:(?:-|/|\,)(?:[0-5]?\d))?)*)\s+(\?|\*|(?:[0-5]?\d)(?:(?:-|/|\,)(?:[0-5]?\d))?(?:,(?:[0-5]?\d)(?:(?:-|/|\,)(?:[0-5]?\d))?)*)\s+(\?|\*|(?:[01]?\d|2[0-3])(?:(?:-|/|\,)(?:[01]?\d|2[0-3]))?(?:,(?:[01]?\d|2[0-3])(?:(?:-|/|\,)(?:[01]?\d|2[0-3]))?)*)\s+(\?|\*|(?:0?[1-9]|[12]\d|3[01])(?:(?:-|/|\,)(?:0?[1-9]|[12]\d|3[01]))?(?:,(?:0?[1-9]|[12]\d|3[01])(?:(?:-|/|\,)(?:0?[1-9]|[12]\d|3[01]))?)*)\s+(\?|\*|(?:[1-9]|1[012])(?:(?:-|/|\,)(?:[1-9]|1[012]))?(?:L|W)?(?:,(?:[1-9]|1[012])(?:(?:-|/|\,)(?:[1-9]|1[012]))?(?:L|W)?)*|\?|\*|(?:JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(?:(?:-)(?:JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?(?:,(?:JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(?:(?:-)(?:JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?)*)\s+(\?|\*|(?:[0-6])(?:(?:-|/|\,|#)(?:[0-6]))?(?:L)?(?:,(?:[0-6])(?:(?:-|/|\,|#)(?:[0-6]))?(?:L)?)*|\?|\*|(?:MON|TUE|WED|THU|FRI|SAT|SUN)(?:(?:-)(?:MON|TUE|WED|THU|FRI|SAT|SUN))?(?:,(?:MON|TUE|WED|THU|FRI|SAT|SUN)(?:(?:-)(?:MON|TUE|WED|THU|FRI|SAT|SUN))?)*)(|\s)+(\?|\*|(?:|\d{4})(?:(?:-|/|\,)(?:|\d{4}))?(?:,(?:|\d{4})(?:(?:-|/|\,)(?:|\d{4}))?)*))\))$
    Default: rate(1 day)
Resources:
  Lambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaPolicy
    Properties:
      Description: Lambda to export Details Org to JSON
      Code:
        S3Bucket:  !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key:  !Ref LamdaZipFileKey
      FunctionName: AWS-LZ-Organization-Exporter
      Handler: index.lambda_handler
      MemorySize: 256
      Timeout: 900
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.9
      Architectures:
      - arm64
      Environment:
        Variables:
          BUCKETNAME: !Ref TargetBucket
          OBJECT: !Ref ObjectName

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/lambda/AWS-LZ-Organization-Exporter'
      RetentionInDays: 1

  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn: LambdaRole
    Properties:
      PolicyName: LambdaPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              -  "organizations:ListPoliciesForTarget"
              -  "organizations:DescribeEffectivePolicy"
              -  "organizations:ListRoots"
              -  "organizations:ListTargetsForPolicy"
              -  "organizations:ListTagsForResource"
              -  "organizations:ListDelegatedServicesForAccount"
              -  "organizations:DescribeAccount"
              -  "organizations:ListAWSServiceAccessForOrganization"
              -  "organizations:DescribePolicy"
              -  "organizations:ListChildren"
              -  "organizations:ListPolicies"
              -  "organizations:ListAccountsForParent"
              -  "organizations:ListHandshakesForOrganization"
              -  "organizations:ListDelegatedAdministrators"
              -  "organizations:ListHandshakesForAccount"
              -  "organizations:ListAccounts"
              -  "organizations:ListCreateAccountStatus"
              -  "organizations:DescribeOrganization"
              -  "organizations:DescribeOrganizationalUnit"
              -  "organizations:ListParents"
              -  "organizations:ListOrganizationalUnitsForParent"
              -  "organizations:DescribeHandshake"
              -  "organizations:DescribeCreateAccountStatus"
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:Get*"
              - "s3:PutObjectAcl"
            Resource:
              - !Sub 'arn:aws:s3:::${TargetBucket}/*'
      Roles:
        - !Ref LambdaRole

  LambdaRole:
    Type: AWS::IAM::Role
    DependsOn: LambdaLogGroup
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com


  LambdaScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "OrgaExportScheduledRule"
      Description: "OrgaExportScheduledRule"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - "Lambda"
              - "Arn"
          Id: "OrgaExportScheduledRule"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        !Ref Lambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "LambdaScheduledRule"
          - "Arn"